os:
  - linux
  - osx

language: node_js
node_js:
  - "6"
  - "8"
  - "9"

before_install:
  - npm i -g npx

script:
  - npm run test:coverage

after_script:
  - cat coverage/lcov.info | npx coveralls

notifications:
  email: false