language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"

env:
  - NODE_ENV=development

install:
  - npm i

script:
  - npm run test:coverage

after_script:
  - cat coverage/lcov.info | npx coveralls

notifications:
  email: false