environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm i -g npx

test_script:
  - npm i

build: off
