environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "13"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm i

test_script:
  - npm t

build: off
